General cleanup, refactor rewrite:
vladamatena/uart_nic pull request #1
Opened 2022-05-05 16:55 UTC by vladamatena

- Rename to uart_nic
- Update sdkconfig to match new SDK
- Add dedicated thread for ESP "ping"
- Remove unused code
- Restore default config on start
- Enable wifi reconfiguration
- Unify logging
- Remove unused stats generator
- Avoid initializing LwIP, optimalize wifi access
- Simplify startup
- Drop unused event group
- Drop unnecessary uart lock existence checks
- Avoid sendLink forward declaration
- tap: set mtu to 1420
- Unify names, add description

2022-05-26 12:46 UTC, vorner requested changes
In general, this seems like a good thing. There are few minor details (or, maybe not so minor ‒ the locking seems to be broken, but very local and probably not hard to fix).

2022-05-30 12:52 UTC, vladamatena commented on main/uart_nic.c
> +    esp_wifi_restore();
Yes, it sounds suspicious. Actually, the documentation says "Restore WiFi stack persistent settings to default values".

2022-05-30 13:07 UTC, vladamatena commented on main/uart_nic.c
> +    send_device_info();
Wait is hopefully a leftover from past. It should work without initial delay.

Main thread just deletes itself after exit. It should not affect already running threads.

2022-05-30 13:11 UTC, vladamatena commented on main/uart_nic.c
> +    read_uart(wifi_config.sta.ssid, ssid_len);
Good point this was not checked, fixed.

2022-05-30 13:11 UTC, vladamatena commented on main/uart_nic.c
> +            if(read != len) {
Condition fixed

2022-05-30 13:13 UTC, vladamatena commented on main/uart_nic.c
> +    return trr;
Fixed, originally this was hacked for endless retries. Fixed to return after a failed read.

2022-05-30 13:14 UTC, vladamatena commented on main/uart_nic.c
> +    }
Comment fixed. Pass initial (zeroes) mac value, lets hope it will work better next time.

2022-05-30 16:55 UTC, vladamatena commented on main/uart_nic.c
> +    xSemaphoreGive(uart_mtx);
Use mutex when accessing uart tx.

2022-05-30 16:56 UTC, vladamatena commented on main/uart_nic.c
> +    //xSemaphoreTakeFromISR(uart_mtx, portMAX_DELAY);
Use mutex when accessing uart tx.

2022-05-30 16:57 UTC, vladamatena commented on main/uart_nic.c
> +static const uint16_t FW_VERSION = 1;
API is the same, I suggest to update version in master when we decide to make a release.

2022-05-30 16:57 UTC, vladamatena commented on main/uart_nic.c
> +    read_uart(wifi_config.sta.password, pass_len);
Fixed

2022-05-30 16:57 UTC, vladamatena commented on main/uart_nic.c
> +            //xSemaphoreTake(uart_mtx, portMAX_DELAY);
Use mutex when accessing uart tx.

2022-06-04 09:34 UTC, vorner approved these changes

2022-06-06 09:23 UTC, merged